files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/Test_Led
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 826169EE29518F275B633373922E70AF
  logicalPath: config/Test_Led
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 826169EE29518F275B633373922E70AF
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/Test_Led
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 283DF3113B63A68D1DDA854ECCA7F4AF
  logicalPath: config/Test_Led/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 283DF3113B63A68D1DDA854ECCA7F4AF
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/Test_Led/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 466C19B09D398839B84748312BC83120
  logicalPath: config/Test_Led/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 466C19B09D398839B84748312BC83120
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/Test_Led/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: D87F97F61F02CE00FB805C95D75191EB
  logicalPath: config/Test_Led
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D87F97F61F02CE00FB805C95D75191EB
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/Test_Led
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/Test_Led
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/Test_Led/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: C8175D686FECDA56EC0FED1578D4ECA7
  logicalPath: config/Test_Led/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: C8175D686FECDA56EC0FED1578D4ECA7
- generatedChecksum: 641C87717DD7C17C492C77ECC95915F2
  logicalPath: config/Test_Led/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 641C87717DD7C17C492C77ECC95915F2
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/Test_Led
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 9F589ECE44A3EEC58F8261C1EAF679B5
  logicalPath: config/Test_Led
  name: p32MZ1024EFM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 9F589ECE44A3EEC58F8261C1EAF679B5
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/Test_Led;../src/packs/PIC32MZ1024EFM100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/Test_Led;../src/packs/PIC32MZ1024EFM100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
