M48
; DRILL file {KiCad 6.0.8+dfsg-1~bpo11+1} date mer. 16 nov. 2022 21:16:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-16T21:16:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.5884Y-5.365
X4.7616Y-5.365
T2
X7.125Y-5.3591
X7.525Y-5.3591
T0
M30
