#ifndef _COMMON_H    /* Guard against multiple inclusion */
#define _COMMON_H

#define TEMP_SENSOR_STREAM_SIZE 3
#define TEMP_SENSOR_CPU 0
#define TEMP_SENSOR_EXT1 TEMP_SENSOR_STREAM_SIZE
#define TEMP_SENSOR_EXT2 TEMP_SENSOR_STREAM_SIZE*2
#define TEMP_SENSOR_EXT3 TEMP_SENSOR_STREAM_SIZE*3
#define TEMP_SENSOR_EXT4 TEMP_SENSOR_STREAM_SIZE*4
#define TEMP_SENSOR_EXT5 TEMP_SENSOR_STREAM_SIZE*5
#define TEMP_SENSOR_EXT6 TEMP_SENSOR_STREAM_SIZE*6
#define TEMP_SENSOR_EXT7 TEMP_SENSOR_STREAM_SIZE*7



#endif 